ALTER TABLE "user"
  ADD COLUMN IF NOT EXISTS "display_name" text,
  ADD COLUMN IF NOT EXISTS "cover_image_url" text,
  ADD COLUMN IF NOT EXISTS "specialty" jsonb,
  ADD COLUMN IF NOT EXISTS "years_experience" integer,
  ADD COLUMN IF NOT EXISTS "city" text,
  ADD COLUMN IF NOT EXISTS "state" text,
  ADD COLUMN IF NOT EXISTS "instagram_url" text,
  ADD COLUMN IF NOT EXISTS "whatsapp_number" text,
  ADD COLUMN IF NOT EXISTS "website_url" text,
  ADD COLUMN IF NOT EXISTS "cpf_cnpj" text,
  ADD COLUMN IF NOT EXISTS "billing_name" text,
  ADD COLUMN IF NOT EXISTS "billing_email" text,
  ADD COLUMN IF NOT EXISTS "billing_address_line1" text,
  ADD COLUMN IF NOT EXISTS "billing_address_city" text,
  ADD COLUMN IF NOT EXISTS "billing_address_state" text,
  ADD COLUMN IF NOT EXISTS "billing_address_zip" text,
  ADD COLUMN IF NOT EXISTS "is_blocked" boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "blocked_reason" text,
  ADD COLUMN IF NOT EXISTS "onboarding_completed" boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "profile_completeness" integer NOT NULL DEFAULT 0;
