/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as LSlugRouteImport } from './routes/l.$slug'
import { Route as ApiPropertyImagesRouteImport } from './routes/api/property-images'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as AdminUsoRouteImport } from './routes/admin.uso'
import { Route as AdminSuporteRouteImport } from './routes/admin.suporte'
import { Route as AdminPlanosRouteImport } from './routes/admin.planos'
import { Route as AdminFinanceiroRouteImport } from './routes/admin.financeiro'
import { Route as AdminEquipeRouteImport } from './routes/admin.equipe'
import { Route as AdminConteudoRouteImport } from './routes/admin.conteudo'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin.configuracoes'
import { Route as AdminAssinaturasRouteImport } from './routes/admin.assinaturas'
import { Route as AppRelatoriosRouteImport } from './routes/_app.relatorios'
import { Route as AppPlanosRouteImport } from './routes/_app.planos'
import { Route as AppPerfilRouteImport } from './routes/_app.perfil'
import { Route as AppMeuLinkRouteImport } from './routes/_app.meu-link'
import { Route as AppLeadsRouteImport } from './routes/_app.leads'
import { Route as AppIntegracoesRouteImport } from './routes/_app.integracoes'
import { Route as AppImoveisRouteImport } from './routes/_app.imoveis'
import { Route as AppExtensaoRouteImport } from './routes/_app.extensao'
import { Route as AppDominioVitrineRouteImport } from './routes/_app.dominio-vitrine'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppConfiguracoesRouteImport } from './routes/_app.configuracoes'
import { Route as AppAutomacoesRouteImport } from './routes/_app.automacoes'
import { Route as AppAgendaRouteImport } from './routes/_app.agenda'
import { Route as LSlugVitrineRouteImport } from './routes/l.$slug_.vitrine'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'
import { Route as ApiExtensionPropertiesRouteImport } from './routes/api/extension/properties'
import { Route as ApiExtensionMeRouteImport } from './routes/api/extension/me'
import { Route as ApiExtensionLeadsRouteImport } from './routes/api/extension/leads'
import { Route as ApiExtensionAuthRouteImport } from './routes/api/extension/auth'
import { Route as ApiExtensionAppointmentsRouteImport } from './routes/api/extension/appointments'
import { Route as AdminCorretoresUserIdRouteImport } from './routes/admin.corretores.$userId'
import { Route as AppLeadsLeadIdRouteImport } from './routes/_app.leads.$leadId'
import { Route as LSlugVitrinePropertyIdRouteImport } from './routes/l.$slug_.vitrine_.$propertyId'
import { Route as ApiExtensionLeadsIdRouteImport } from './routes/api/extension/leads.$id'
import { Route as ApiExtensionAiAnalyzeRouteImport } from './routes/api/extension/ai.analyze'
import { Route as ApiExtensionLeadsByPhonePhoneRouteImport } from './routes/api/extension/leads.by-phone.$phone'
import { Route as ApiExtensionLeadsIdActivityRouteImport } from './routes/api/extension/leads.$id.activity'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const LSlugRoute = LSlugRouteImport.update({
  id: '/l/$slug',
  path: '/l/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPropertyImagesRoute = ApiPropertyImagesRouteImport.update({
  id: '/api/property-images',
  path: '/api/property-images',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsoRoute = AdminUsoRouteImport.update({
  id: '/uso',
  path: '/uso',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSuporteRoute = AdminSuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlanosRoute = AdminPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceiroRoute = AdminFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEquipeRoute = AdminEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConteudoRoute = AdminConteudoRouteImport.update({
  id: '/conteudo',
  path: '/conteudo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAssinaturasRoute = AdminAssinaturasRouteImport.update({
  id: '/assinaturas',
  path: '/assinaturas',
  getParentRoute: () => AdminRoute,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppPlanosRoute = AppPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppMeuLinkRoute = AppMeuLinkRouteImport.update({
  id: '/meu-link',
  path: '/meu-link',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsRoute = AppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegracoesRoute = AppIntegracoesRouteImport.update({
  id: '/integracoes',
  path: '/integracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppImoveisRoute = AppImoveisRouteImport.update({
  id: '/imoveis',
  path: '/imoveis',
  getParentRoute: () => AppRoute,
} as any)
const AppExtensaoRoute = AppExtensaoRouteImport.update({
  id: '/extensao',
  path: '/extensao',
  getParentRoute: () => AppRoute,
} as any)
const AppDominioVitrineRoute = AppDominioVitrineRouteImport.update({
  id: '/dominio-vitrine',
  path: '/dominio-vitrine',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppAutomacoesRoute = AppAutomacoesRouteImport.update({
  id: '/automacoes',
  path: '/automacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppAgendaRoute = AppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AppRoute,
} as any)
const LSlugVitrineRoute = LSlugVitrineRouteImport.update({
  id: '/l/$slug_/vitrine',
  path: '/l/$slug/vitrine',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExtensionPropertiesRoute = ApiExtensionPropertiesRouteImport.update({
  id: '/api/extension/properties',
  path: '/api/extension/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExtensionMeRoute = ApiExtensionMeRouteImport.update({
  id: '/api/extension/me',
  path: '/api/extension/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExtensionLeadsRoute = ApiExtensionLeadsRouteImport.update({
  id: '/api/extension/leads',
  path: '/api/extension/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExtensionAuthRoute = ApiExtensionAuthRouteImport.update({
  id: '/api/extension/auth',
  path: '/api/extension/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExtensionAppointmentsRoute =
  ApiExtensionAppointmentsRouteImport.update({
    id: '/api/extension/appointments',
    path: '/api/extension/appointments',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminCorretoresUserIdRoute = AdminCorretoresUserIdRouteImport.update({
  id: '/corretores/$userId',
  path: '/corretores/$userId',
  getParentRoute: () => AdminRoute,
} as any)
const AppLeadsLeadIdRoute = AppLeadsLeadIdRouteImport.update({
  id: '/$leadId',
  path: '/$leadId',
  getParentRoute: () => AppLeadsRoute,
} as any)
const LSlugVitrinePropertyIdRoute = LSlugVitrinePropertyIdRouteImport.update({
  id: '/l/$slug_/vitrine_/$propertyId',
  path: '/l/$slug/vitrine/$propertyId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExtensionLeadsIdRoute = ApiExtensionLeadsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiExtensionLeadsRoute,
} as any)
const ApiExtensionAiAnalyzeRoute = ApiExtensionAiAnalyzeRouteImport.update({
  id: '/api/extension/ai/analyze',
  path: '/api/extension/ai/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExtensionLeadsByPhonePhoneRoute =
  ApiExtensionLeadsByPhonePhoneRouteImport.update({
    id: '/by-phone/$phone',
    path: '/by-phone/$phone',
    getParentRoute: () => ApiExtensionLeadsRoute,
  } as any)
const ApiExtensionLeadsIdActivityRoute =
  ApiExtensionLeadsIdActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => ApiExtensionLeadsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/agenda': typeof AppAgendaRoute
  '/automacoes': typeof AppAutomacoesRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/dashboard': typeof AppDashboardRoute
  '/dominio-vitrine': typeof AppDominioVitrineRoute
  '/extensao': typeof AppExtensaoRoute
  '/imoveis': typeof AppImoveisRoute
  '/integracoes': typeof AppIntegracoesRoute
  '/leads': typeof AppLeadsRouteWithChildren
  '/meu-link': typeof AppMeuLinkRoute
  '/perfil': typeof AppPerfilRoute
  '/planos': typeof AppPlanosRoute
  '/relatorios': typeof AppRelatoriosRoute
  '/admin/assinaturas': typeof AdminAssinaturasRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/conteudo': typeof AdminConteudoRoute
  '/admin/equipe': typeof AdminEquipeRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/planos': typeof AdminPlanosRoute
  '/admin/suporte': typeof AdminSuporteRoute
  '/admin/uso': typeof AdminUsoRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/api/property-images': typeof ApiPropertyImagesRoute
  '/l/$slug': typeof LSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/leads/$leadId': typeof AppLeadsLeadIdRoute
  '/admin/corretores/$userId': typeof AdminCorretoresUserIdRoute
  '/api/extension/appointments': typeof ApiExtensionAppointmentsRoute
  '/api/extension/auth': typeof ApiExtensionAuthRoute
  '/api/extension/leads': typeof ApiExtensionLeadsRouteWithChildren
  '/api/extension/me': typeof ApiExtensionMeRoute
  '/api/extension/properties': typeof ApiExtensionPropertiesRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/l/$slug/vitrine': typeof LSlugVitrineRoute
  '/api/extension/ai/analyze': typeof ApiExtensionAiAnalyzeRoute
  '/api/extension/leads/$id': typeof ApiExtensionLeadsIdRouteWithChildren
  '/l/$slug/vitrine/$propertyId': typeof LSlugVitrinePropertyIdRoute
  '/api/extension/leads/$id/activity': typeof ApiExtensionLeadsIdActivityRoute
  '/api/extension/leads/by-phone/$phone': typeof ApiExtensionLeadsByPhonePhoneRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/agenda': typeof AppAgendaRoute
  '/automacoes': typeof AppAutomacoesRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/dashboard': typeof AppDashboardRoute
  '/dominio-vitrine': typeof AppDominioVitrineRoute
  '/extensao': typeof AppExtensaoRoute
  '/imoveis': typeof AppImoveisRoute
  '/integracoes': typeof AppIntegracoesRoute
  '/leads': typeof AppLeadsRouteWithChildren
  '/meu-link': typeof AppMeuLinkRoute
  '/perfil': typeof AppPerfilRoute
  '/planos': typeof AppPlanosRoute
  '/relatorios': typeof AppRelatoriosRoute
  '/admin/assinaturas': typeof AdminAssinaturasRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/conteudo': typeof AdminConteudoRoute
  '/admin/equipe': typeof AdminEquipeRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/planos': typeof AdminPlanosRoute
  '/admin/suporte': typeof AdminSuporteRoute
  '/admin/uso': typeof AdminUsoRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/api/property-images': typeof ApiPropertyImagesRoute
  '/l/$slug': typeof LSlugRoute
  '/admin': typeof AdminIndexRoute
  '/leads/$leadId': typeof AppLeadsLeadIdRoute
  '/admin/corretores/$userId': typeof AdminCorretoresUserIdRoute
  '/api/extension/appointments': typeof ApiExtensionAppointmentsRoute
  '/api/extension/auth': typeof ApiExtensionAuthRoute
  '/api/extension/leads': typeof ApiExtensionLeadsRouteWithChildren
  '/api/extension/me': typeof ApiExtensionMeRoute
  '/api/extension/properties': typeof ApiExtensionPropertiesRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/l/$slug/vitrine': typeof LSlugVitrineRoute
  '/api/extension/ai/analyze': typeof ApiExtensionAiAnalyzeRoute
  '/api/extension/leads/$id': typeof ApiExtensionLeadsIdRouteWithChildren
  '/l/$slug/vitrine/$propertyId': typeof LSlugVitrinePropertyIdRoute
  '/api/extension/leads/$id/activity': typeof ApiExtensionLeadsIdActivityRoute
  '/api/extension/leads/by-phone/$phone': typeof ApiExtensionLeadsByPhonePhoneRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/agenda': typeof AppAgendaRoute
  '/_app/automacoes': typeof AppAutomacoesRoute
  '/_app/configuracoes': typeof AppConfiguracoesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/dominio-vitrine': typeof AppDominioVitrineRoute
  '/_app/extensao': typeof AppExtensaoRoute
  '/_app/imoveis': typeof AppImoveisRoute
  '/_app/integracoes': typeof AppIntegracoesRoute
  '/_app/leads': typeof AppLeadsRouteWithChildren
  '/_app/meu-link': typeof AppMeuLinkRoute
  '/_app/perfil': typeof AppPerfilRoute
  '/_app/planos': typeof AppPlanosRoute
  '/_app/relatorios': typeof AppRelatoriosRoute
  '/admin/assinaturas': typeof AdminAssinaturasRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/conteudo': typeof AdminConteudoRoute
  '/admin/equipe': typeof AdminEquipeRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/planos': typeof AdminPlanosRoute
  '/admin/suporte': typeof AdminSuporteRoute
  '/admin/uso': typeof AdminUsoRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/api/property-images': typeof ApiPropertyImagesRoute
  '/l/$slug': typeof LSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/_app/leads/$leadId': typeof AppLeadsLeadIdRoute
  '/admin/corretores/$userId': typeof AdminCorretoresUserIdRoute
  '/api/extension/appointments': typeof ApiExtensionAppointmentsRoute
  '/api/extension/auth': typeof ApiExtensionAuthRoute
  '/api/extension/leads': typeof ApiExtensionLeadsRouteWithChildren
  '/api/extension/me': typeof ApiExtensionMeRoute
  '/api/extension/properties': typeof ApiExtensionPropertiesRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/l/$slug_/vitrine': typeof LSlugVitrineRoute
  '/api/extension/ai/analyze': typeof ApiExtensionAiAnalyzeRoute
  '/api/extension/leads/$id': typeof ApiExtensionLeadsIdRouteWithChildren
  '/l/$slug_/vitrine_/$propertyId': typeof LSlugVitrinePropertyIdRoute
  '/api/extension/leads/$id/activity': typeof ApiExtensionLeadsIdActivityRoute
  '/api/extension/leads/by-phone/$phone': typeof ApiExtensionLeadsByPhonePhoneRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/agenda'
    | '/automacoes'
    | '/configuracoes'
    | '/dashboard'
    | '/dominio-vitrine'
    | '/extensao'
    | '/imoveis'
    | '/integracoes'
    | '/leads'
    | '/meu-link'
    | '/perfil'
    | '/planos'
    | '/relatorios'
    | '/admin/assinaturas'
    | '/admin/configuracoes'
    | '/admin/conteudo'
    | '/admin/equipe'
    | '/admin/financeiro'
    | '/admin/planos'
    | '/admin/suporte'
    | '/admin/uso'
    | '/admin/usuarios'
    | '/api/property-images'
    | '/l/$slug'
    | '/admin/'
    | '/leads/$leadId'
    | '/admin/corretores/$userId'
    | '/api/extension/appointments'
    | '/api/extension/auth'
    | '/api/extension/leads'
    | '/api/extension/me'
    | '/api/extension/properties'
    | '/api/stripe/webhook'
    | '/l/$slug/vitrine'
    | '/api/extension/ai/analyze'
    | '/api/extension/leads/$id'
    | '/l/$slug/vitrine/$propertyId'
    | '/api/extension/leads/$id/activity'
    | '/api/extension/leads/by-phone/$phone'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/agenda'
    | '/automacoes'
    | '/configuracoes'
    | '/dashboard'
    | '/dominio-vitrine'
    | '/extensao'
    | '/imoveis'
    | '/integracoes'
    | '/leads'
    | '/meu-link'
    | '/perfil'
    | '/planos'
    | '/relatorios'
    | '/admin/assinaturas'
    | '/admin/configuracoes'
    | '/admin/conteudo'
    | '/admin/equipe'
    | '/admin/financeiro'
    | '/admin/planos'
    | '/admin/suporte'
    | '/admin/uso'
    | '/admin/usuarios'
    | '/api/property-images'
    | '/l/$slug'
    | '/admin'
    | '/leads/$leadId'
    | '/admin/corretores/$userId'
    | '/api/extension/appointments'
    | '/api/extension/auth'
    | '/api/extension/leads'
    | '/api/extension/me'
    | '/api/extension/properties'
    | '/api/stripe/webhook'
    | '/l/$slug/vitrine'
    | '/api/extension/ai/analyze'
    | '/api/extension/leads/$id'
    | '/l/$slug/vitrine/$propertyId'
    | '/api/extension/leads/$id/activity'
    | '/api/extension/leads/by-phone/$phone'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/admin'
    | '/login'
    | '/_app/agenda'
    | '/_app/automacoes'
    | '/_app/configuracoes'
    | '/_app/dashboard'
    | '/_app/dominio-vitrine'
    | '/_app/extensao'
    | '/_app/imoveis'
    | '/_app/integracoes'
    | '/_app/leads'
    | '/_app/meu-link'
    | '/_app/perfil'
    | '/_app/planos'
    | '/_app/relatorios'
    | '/admin/assinaturas'
    | '/admin/configuracoes'
    | '/admin/conteudo'
    | '/admin/equipe'
    | '/admin/financeiro'
    | '/admin/planos'
    | '/admin/suporte'
    | '/admin/uso'
    | '/admin/usuarios'
    | '/api/property-images'
    | '/l/$slug'
    | '/admin/'
    | '/_app/leads/$leadId'
    | '/admin/corretores/$userId'
    | '/api/extension/appointments'
    | '/api/extension/auth'
    | '/api/extension/leads'
    | '/api/extension/me'
    | '/api/extension/properties'
    | '/api/stripe/webhook'
    | '/l/$slug_/vitrine'
    | '/api/extension/ai/analyze'
    | '/api/extension/leads/$id'
    | '/l/$slug_/vitrine_/$propertyId'
    | '/api/extension/leads/$id/activity'
    | '/api/extension/leads/by-phone/$phone'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiPropertyImagesRoute: typeof ApiPropertyImagesRoute
  LSlugRoute: typeof LSlugRoute
  ApiExtensionAppointmentsRoute: typeof ApiExtensionAppointmentsRoute
  ApiExtensionAuthRoute: typeof ApiExtensionAuthRoute
  ApiExtensionLeadsRoute: typeof ApiExtensionLeadsRouteWithChildren
  ApiExtensionMeRoute: typeof ApiExtensionMeRoute
  ApiExtensionPropertiesRoute: typeof ApiExtensionPropertiesRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  LSlugVitrineRoute: typeof LSlugVitrineRoute
  ApiExtensionAiAnalyzeRoute: typeof ApiExtensionAiAnalyzeRoute
  LSlugVitrinePropertyIdRoute: typeof LSlugVitrinePropertyIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/l/$slug': {
      id: '/l/$slug'
      path: '/l/$slug'
      fullPath: '/l/$slug'
      preLoaderRoute: typeof LSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/property-images': {
      id: '/api/property-images'
      path: '/api/property-images'
      fullPath: '/api/property-images'
      preLoaderRoute: typeof ApiPropertyImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/uso': {
      id: '/admin/uso'
      path: '/uso'
      fullPath: '/admin/uso'
      preLoaderRoute: typeof AdminUsoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/suporte': {
      id: '/admin/suporte'
      path: '/suporte'
      fullPath: '/admin/suporte'
      preLoaderRoute: typeof AdminSuporteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/planos': {
      id: '/admin/planos'
      path: '/planos'
      fullPath: '/admin/planos'
      preLoaderRoute: typeof AdminPlanosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/financeiro': {
      id: '/admin/financeiro'
      path: '/financeiro'
      fullPath: '/admin/financeiro'
      preLoaderRoute: typeof AdminFinanceiroRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/equipe': {
      id: '/admin/equipe'
      path: '/equipe'
      fullPath: '/admin/equipe'
      preLoaderRoute: typeof AdminEquipeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/conteudo': {
      id: '/admin/conteudo'
      path: '/conteudo'
      fullPath: '/admin/conteudo'
      preLoaderRoute: typeof AdminConteudoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/assinaturas': {
      id: '/admin/assinaturas'
      path: '/assinaturas'
      fullPath: '/admin/assinaturas'
      preLoaderRoute: typeof AdminAssinaturasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/relatorios': {
      id: '/_app/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/planos': {
      id: '/_app/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof AppPlanosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/perfil': {
      id: '/_app/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/meu-link': {
      id: '/_app/meu-link'
      path: '/meu-link'
      fullPath: '/meu-link'
      preLoaderRoute: typeof AppMeuLinkRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads': {
      id: '/_app/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AppLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integracoes': {
      id: '/_app/integracoes'
      path: '/integracoes'
      fullPath: '/integracoes'
      preLoaderRoute: typeof AppIntegracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/imoveis': {
      id: '/_app/imoveis'
      path: '/imoveis'
      fullPath: '/imoveis'
      preLoaderRoute: typeof AppImoveisRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/extensao': {
      id: '/_app/extensao'
      path: '/extensao'
      fullPath: '/extensao'
      preLoaderRoute: typeof AppExtensaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dominio-vitrine': {
      id: '/_app/dominio-vitrine'
      path: '/dominio-vitrine'
      fullPath: '/dominio-vitrine'
      preLoaderRoute: typeof AppDominioVitrineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracoes': {
      id: '/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/automacoes': {
      id: '/_app/automacoes'
      path: '/automacoes'
      fullPath: '/automacoes'
      preLoaderRoute: typeof AppAutomacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agenda': {
      id: '/_app/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AppAgendaRouteImport
      parentRoute: typeof AppRoute
    }
    '/l/$slug_/vitrine': {
      id: '/l/$slug_/vitrine'
      path: '/l/$slug/vitrine'
      fullPath: '/l/$slug/vitrine'
      preLoaderRoute: typeof LSlugVitrineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/extension/properties': {
      id: '/api/extension/properties'
      path: '/api/extension/properties'
      fullPath: '/api/extension/properties'
      preLoaderRoute: typeof ApiExtensionPropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/extension/me': {
      id: '/api/extension/me'
      path: '/api/extension/me'
      fullPath: '/api/extension/me'
      preLoaderRoute: typeof ApiExtensionMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/extension/leads': {
      id: '/api/extension/leads'
      path: '/api/extension/leads'
      fullPath: '/api/extension/leads'
      preLoaderRoute: typeof ApiExtensionLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/extension/auth': {
      id: '/api/extension/auth'
      path: '/api/extension/auth'
      fullPath: '/api/extension/auth'
      preLoaderRoute: typeof ApiExtensionAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/extension/appointments': {
      id: '/api/extension/appointments'
      path: '/api/extension/appointments'
      fullPath: '/api/extension/appointments'
      preLoaderRoute: typeof ApiExtensionAppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/corretores/$userId': {
      id: '/admin/corretores/$userId'
      path: '/corretores/$userId'
      fullPath: '/admin/corretores/$userId'
      preLoaderRoute: typeof AdminCorretoresUserIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/leads/$leadId': {
      id: '/_app/leads/$leadId'
      path: '/$leadId'
      fullPath: '/leads/$leadId'
      preLoaderRoute: typeof AppLeadsLeadIdRouteImport
      parentRoute: typeof AppLeadsRoute
    }
    '/l/$slug_/vitrine_/$propertyId': {
      id: '/l/$slug_/vitrine_/$propertyId'
      path: '/l/$slug/vitrine/$propertyId'
      fullPath: '/l/$slug/vitrine/$propertyId'
      preLoaderRoute: typeof LSlugVitrinePropertyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/extension/leads/$id': {
      id: '/api/extension/leads/$id'
      path: '/$id'
      fullPath: '/api/extension/leads/$id'
      preLoaderRoute: typeof ApiExtensionLeadsIdRouteImport
      parentRoute: typeof ApiExtensionLeadsRoute
    }
    '/api/extension/ai/analyze': {
      id: '/api/extension/ai/analyze'
      path: '/api/extension/ai/analyze'
      fullPath: '/api/extension/ai/analyze'
      preLoaderRoute: typeof ApiExtensionAiAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/extension/leads/by-phone/$phone': {
      id: '/api/extension/leads/by-phone/$phone'
      path: '/by-phone/$phone'
      fullPath: '/api/extension/leads/by-phone/$phone'
      preLoaderRoute: typeof ApiExtensionLeadsByPhonePhoneRouteImport
      parentRoute: typeof ApiExtensionLeadsRoute
    }
    '/api/extension/leads/$id/activity': {
      id: '/api/extension/leads/$id/activity'
      path: '/activity'
      fullPath: '/api/extension/leads/$id/activity'
      preLoaderRoute: typeof ApiExtensionLeadsIdActivityRouteImport
      parentRoute: typeof ApiExtensionLeadsIdRoute
    }
  }
}

interface AppLeadsRouteChildren {
  AppLeadsLeadIdRoute: typeof AppLeadsLeadIdRoute
}

const AppLeadsRouteChildren: AppLeadsRouteChildren = {
  AppLeadsLeadIdRoute: AppLeadsLeadIdRoute,
}

const AppLeadsRouteWithChildren = AppLeadsRoute._addFileChildren(
  AppLeadsRouteChildren,
)

interface AppRouteChildren {
  AppAgendaRoute: typeof AppAgendaRoute
  AppAutomacoesRoute: typeof AppAutomacoesRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDominioVitrineRoute: typeof AppDominioVitrineRoute
  AppExtensaoRoute: typeof AppExtensaoRoute
  AppImoveisRoute: typeof AppImoveisRoute
  AppIntegracoesRoute: typeof AppIntegracoesRoute
  AppLeadsRoute: typeof AppLeadsRouteWithChildren
  AppMeuLinkRoute: typeof AppMeuLinkRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppPlanosRoute: typeof AppPlanosRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgendaRoute: AppAgendaRoute,
  AppAutomacoesRoute: AppAutomacoesRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDominioVitrineRoute: AppDominioVitrineRoute,
  AppExtensaoRoute: AppExtensaoRoute,
  AppImoveisRoute: AppImoveisRoute,
  AppIntegracoesRoute: AppIntegracoesRoute,
  AppLeadsRoute: AppLeadsRouteWithChildren,
  AppMeuLinkRoute: AppMeuLinkRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppPlanosRoute: AppPlanosRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AdminRouteChildren {
  AdminAssinaturasRoute: typeof AdminAssinaturasRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminConteudoRoute: typeof AdminConteudoRoute
  AdminEquipeRoute: typeof AdminEquipeRoute
  AdminFinanceiroRoute: typeof AdminFinanceiroRoute
  AdminPlanosRoute: typeof AdminPlanosRoute
  AdminSuporteRoute: typeof AdminSuporteRoute
  AdminUsoRoute: typeof AdminUsoRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCorretoresUserIdRoute: typeof AdminCorretoresUserIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAssinaturasRoute: AdminAssinaturasRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminConteudoRoute: AdminConteudoRoute,
  AdminEquipeRoute: AdminEquipeRoute,
  AdminFinanceiroRoute: AdminFinanceiroRoute,
  AdminPlanosRoute: AdminPlanosRoute,
  AdminSuporteRoute: AdminSuporteRoute,
  AdminUsoRoute: AdminUsoRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCorretoresUserIdRoute: AdminCorretoresUserIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ApiExtensionLeadsIdRouteChildren {
  ApiExtensionLeadsIdActivityRoute: typeof ApiExtensionLeadsIdActivityRoute
}

const ApiExtensionLeadsIdRouteChildren: ApiExtensionLeadsIdRouteChildren = {
  ApiExtensionLeadsIdActivityRoute: ApiExtensionLeadsIdActivityRoute,
}

const ApiExtensionLeadsIdRouteWithChildren =
  ApiExtensionLeadsIdRoute._addFileChildren(ApiExtensionLeadsIdRouteChildren)

interface ApiExtensionLeadsRouteChildren {
  ApiExtensionLeadsIdRoute: typeof ApiExtensionLeadsIdRouteWithChildren
  ApiExtensionLeadsByPhonePhoneRoute: typeof ApiExtensionLeadsByPhonePhoneRoute
}

const ApiExtensionLeadsRouteChildren: ApiExtensionLeadsRouteChildren = {
  ApiExtensionLeadsIdRoute: ApiExtensionLeadsIdRouteWithChildren,
  ApiExtensionLeadsByPhonePhoneRoute: ApiExtensionLeadsByPhonePhoneRoute,
}

const ApiExtensionLeadsRouteWithChildren =
  ApiExtensionLeadsRoute._addFileChildren(ApiExtensionLeadsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiPropertyImagesRoute: ApiPropertyImagesRoute,
  LSlugRoute: LSlugRoute,
  ApiExtensionAppointmentsRoute: ApiExtensionAppointmentsRoute,
  ApiExtensionAuthRoute: ApiExtensionAuthRoute,
  ApiExtensionLeadsRoute: ApiExtensionLeadsRouteWithChildren,
  ApiExtensionMeRoute: ApiExtensionMeRoute,
  ApiExtensionPropertiesRoute: ApiExtensionPropertiesRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  LSlugVitrineRoute: LSlugVitrineRoute,
  ApiExtensionAiAnalyzeRoute: ApiExtensionAiAnalyzeRoute,
  LSlugVitrinePropertyIdRoute: LSlugVitrinePropertyIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
